version: '3.7'

services:
  django:
    build:
      context: ./backend
    image: contacts_backend
    container_name: contacts_django
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    container_name: contacts_redis