# Generated by Django 4.2 on 2024-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_created_by_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
